---
- name: ensure oh-my-zsh
  block:
    - import_tasks: environment.yml
    - import_tasks: packages.yml
    - import_tasks: directories.yml
    - import_tasks: configuration.yml
    - import_tasks: oh-my-zsh.yml
    - import_tasks: shell.yml
  tags:
    - oh-my-zsh
