---
- name: ensure oh-my-zsh is installed and configured
  block:

  - file:
      path: "/etc/zsh"
      state: "directory"

  - name: ensure oh-my-zsh repository is cloned
    git:
      repo: "{{ oh_my_zsh_repository }}"
      dest: "{{ oh_my_zsh_directory }}"
      update: false

  - name: ensure oh-my-zsh repository is up to date
    git:
      repo: "{{ oh_my_zsh_repository }}"
      dest: "{{ oh_my_zsh_directory }}"
      clone: false

  - name: ensure global zsh configuration is correct
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
      - { src: "zshrc.j2", dest: "/etc/zsh/zshrc" }
      - { src: "zshenv.j2", dest: "/etc/zsh/zshenv" }
      - { src: "zlogin.j2", dest: "/etc/zsh/zlogin" }
      - { src: "zlogout.j2", dest: "/etc/zsh/zlogout" }

  - file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      force: true
      state: "link"
    with_items:
      - { src: "/etc/zsh/zshenv", dest: "/etc/zshenv" }
      - { src: "/etc/zsh/zshrc", dest: "/etc/zshrc" }
    when: ansible_distribution == 'CentOS'

  become: true
