---
- name: ensure git and zfs packages are installed
  apt:
    pkg: "{{ item }}"
    install_recommends: false
    state: "present"
    update_cache: true
    cache_valid_time: 86400
  with_items:
    - git
    - zsh
  become: true
  when: ansible_distribution == 'Debian'

- name: ensure git and zfs packages are installed
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - git
    - zsh
  become: true
  when: ansible_distribution == 'CentOS'
