---
- name: ensure current user and root is using zsh shell
  user:
    name: "{{ item }}"
    shell: "{{ oh_my_zsh_zsh_shell }}"
  loop:
    - "{{ ansible_env.USER }}"
    - "root"
  become: true
  ignore_errors: true
